a="hello and welcom to the tops technology and in python program"
print(a.count("hello"))
print(a.count("and"))
print(a.count("welcome"))
print(a.count("to"))
print(a.count("the"))
print(a.count("tops"))
print(a.count("technology"))
print(a.count("in"))
print(a.count("python"))
print(a.count("program"))